unseen1980/awesome-travel

README.md

Update hotels api

---

README.md

Units (http://units.d8u.us)
Iwannagothere (http://iwannagothere.com/api/index.html)
Evature (http://freeapi.evature.com/)

Remove Defunct sites

---

README.md

Removing Tgels, updating skyscanner and adding Airbnb

Removing Tgels, updating skyscanner and adding Airbnb

---

README.md

Add exchangeratesapi.io as a new currency api.

Add new currency API

---

README.md

This taxi API seems to be offline. Found something equivalent that appears pretty well documented.

fix link to broken taxi API

---

README.md

A free to use geolocation api.

New geolocation api

---

README.md

Added a new stock photos link, this one even has vectors, and icons

Added freepik link

---

README.md

OpenStreetMap is an open source wiki world map. They provide many different APIs for developers to use such as for accessing geodata, maps, and complex queries.
fixes #3

Added OpenStreetMap as a map service.

---

README.md

Added Points of Interest API link to Travel Planning section of README.md

Add Amadeus to Travel Planning

---

README.md

Added PredictHQ to events section of README.md

Add PredictHQ to Events

---

README.md

Added table with yacht rentals API's

Yacht rentals API's

---

README.md

I added a hotel API which is hotels.com API which I found from rapid API. the link will direct you to rapidapi.com where you can try the API and find some information about it

added a hotels api

---

README.md

I found two broken links showing error, **Page Not Found**. And update README.md and change broken links with working links.
For issue #3 .

Find and Fix Broken Links

---

README.md

I spotted a broken link while testing all links.

Removed a broken link

---

README.md

Add Arcgis, Triposo and Sygic
https://github.com/unseen1980/awesome-travel/issues

Add additional ApI reference

---

README.md

Added new link: Booking.com API

Added Booking.com API

---

README.md

Add **ADS-B Exchange** as new link to the Flights section.
Enjoy and happy coding!

Added new link: ADS-B Exchange

---

README.md

**FIXES ISSUE** #3 partially
**Changes Made**
1. Changed the broken link for `Travelfusion API` and updated it with the link to the doc for the `Travelfusion Search and Book API`.
2. Changes are made to `README.md`
**NOTE**
1. Please consider this PR as a submission towards **Hacktoberfest 2021** and add the `hacktoberfest-accepted` label to it. 
2. **Hacktoberfest 2021** has started as of now globally due to a bug in the timing algorithm so you can merge the PR now and it will still count. Cheers.

fixes partially issue #3

---

LICENCE

In the readme it states that it is under the MIT licence, but there is no licence, so I added one!

Add LICENCE file

---

README.md

I have updated one new link with one old dead link and I have removed one platform as it is not available on the internet. I have searched it many times and tried to open the links still it wasn't opening.

Updated the dead links in readme file

---

README.md

related to #3 
disabled and here, inclusive stock images. Many under CC license.
Also alphabetized the stock photo list.

adding affect the verb 

---

README.md

Lnk for TripAdvisor API under Point of Interests was deprecated. Updated the link to working one.

Fixed TripAdvisor broken link

---

README.md

* Change Foursquare API link to open documentation, not company's homepage  
* Add Famxplor family travel API

Update README.md / POIs
